-- CreateEnum
CREATE TYPE "Difficulty" AS ENUM ('easy', 'medium', 'expert');

-- CreateEnum
CREATE TYPE "Units" AS ENUM ('grams', 'kilograms', 'millilitres', 'litres', 'dimensionless');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('owner', 'editor', 'viewer');

-- CreateTable
CREATE TABLE "Recipes" (
    "id" STRING NOT NULL,
    "title" STRING NOT NULL,
    "description" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "difficulty" "Difficulty" NOT NULL,
    "prepMinutes" INT4 NOT NULL,
    "tags" STRING[],
    "private" BOOL NOT NULL DEFAULT true,

    CONSTRAINT "Recipes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Ingredients" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "units" "Units" NOT NULL,

    CONSTRAINT "Ingredients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Users" (
    "id" STRING NOT NULL,
    "username" STRING NOT NULL,
    "hashedPassword" STRING NOT NULL,
    "fullname" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IngredientRecipe" (
    "amount" FLOAT8 NOT NULL,
    "recipesId" STRING NOT NULL,
    "ingredientsId" INT4 NOT NULL,

    CONSTRAINT "IngredientRecipe_pkey" PRIMARY KEY ("recipesId","ingredientsId")
);

-- CreateTable
CREATE TABLE "RecipeUser" (
    "role" "Role" NOT NULL,
    "usersId" STRING NOT NULL,
    "recipesId" STRING NOT NULL,

    CONSTRAINT "RecipeUser_pkey" PRIMARY KEY ("usersId","recipesId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Users_username_key" ON "Users"("username");

-- AddForeignKey
ALTER TABLE "IngredientRecipe" ADD CONSTRAINT "IngredientRecipe_recipesId_fkey" FOREIGN KEY ("recipesId") REFERENCES "Recipes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IngredientRecipe" ADD CONSTRAINT "IngredientRecipe_ingredientsId_fkey" FOREIGN KEY ("ingredientsId") REFERENCES "Ingredients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeUser" ADD CONSTRAINT "RecipeUser_usersId_fkey" FOREIGN KEY ("usersId") REFERENCES "Users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeUser" ADD CONSTRAINT "RecipeUser_recipesId_fkey" FOREIGN KEY ("recipesId") REFERENCES "Recipes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
